export const MessageRegistrationContext = {
  prov: 'http://www.w3.org/ns/prov#',
  dct: 'http://purl.org/dc/terms/',
  muAccount: 'http://mu.semte.ch/vocabularies/account/',
  dgftOauth: 'http://kanselarij.vo.data.gift/vocabularies/oauth-2.0-session/',
  dgftSec: 'http://lblod.data.gift/vocabularies/security/',
  meb: 'http://rdf.myexperiment.org/ontologies/base/',
  pav: 'http://purl.org/pav/',
  adms: 'http://www.w3.org/ns/adms#',
  wotSec: 'https://www.w3.org/2019/wot/security#',
  core: 'http://mu.semte.ch/vocabularies/core/',
  schema: 'http://schema.org/',
  berichten: 'http://data.lblod.info/id/berichten/',
  conversaties: 'http://data.lblod.info/id/conversaties/',
  auths: 'http://data.lblod.info/authentications/',
  confs: 'http://data.lblod.info/configurations/',
  creds: 'http://data.lblod.info/id/conversaties/',
  organization: {
    '@id': 'pav:authoredBy',
    '@type': '@id',
  },
  href: {
    '@type': '@id',
    '@id': 'prov:atLocation',
  },
  key: 'muAccount:key',
  publisher: 'pav:contributedBy',
  authentication: 'dgftSec:targetAuthenticationConfiguration',
  configuration: 'dgftSec:securityConfiguration',
  credentials: 'dgftSec:secrets',
  acceptedBy: 'dgftSec:acceptedBy',
  oauth2: {
    '@type': '@id',
    '@id': 'wotSec:OAuth2SecurityScheme',
  },
  basic: {
    '@type': '@id',
    '@id': 'wotSec:BasicSecurityScheme',
  },
  flow: 'wotSec:flow',
  token: 'wotSec:token',
  scheme: {
    '@id': '@type',
    '@type': '@vocab',
  },
  resource: 'dgftOauth:resource',
  clientId: 'dgftOauth:clientId',
  clientSecret: 'dgftOauth:clientSecret',
  username: 'meb:username',
  password: 'muAccount:password',
  message: {
    '@type': '@id',
    '@id': 'schema:hasPart',
  },
  type: '@type',
  id: '@id',
};
